#--------------------------------------------------------
# Server
#--------------------------------------------------------
server:
  port: 8080 
  servlet: 
    session: 
      persistent: false
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json

#--------------------------------------------------------
# Spring
#--------------------------------------------------------
spring:
  main:
    web-application-type: reactive

  threads:
    virtual:
      enabled: true

  codec:
    max-in-memory-size: -1 # Remove buffer limits

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 600000    
        response-timeout: 600s # 180s for long polls                
      globalcors:
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173" #local
            #allowed-origins: "https://xxxxxxxx" #production
            allowed-headers: 
              - Authorization
              - Content-Type
              - Accept
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS                                  
              - PATCH

# --------------------------------------------------------------
# Enable Monitoring
# --------------------------------------------------------------
management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  health: 
    circuitbreakers:
      enabled: true

#-------------------------------------------------------
# Gateway custom security configuration properties
#--------------------------------------------------------
gateway:
   security:
      token-subject: api-gateway 
      port-check: true  
      # Whitelisted IPs allowed to access the API Gateway (comma-separated)
      # Includes localhost, IPv6 loopback, and Docker bridge network CIDR (172.16.0.0/12)
      whitelist-ips: 
         - 127.0.0.1
         #- 192.168.1.10
      whitelist-ports:
         - 8080
         
         # Shared secret key used for signing JWT tokens.
         # Must be at least 256 bits (32 bytes) long.
         # Value: "this-secret-is-large-enough-to-be-safe-and-256-bit-secure!" base64 encoded
      shared-secret: "dGhpcy1zZWNyZXQtaXMtbGFyZ2UtZW5vdWdoLXRvLWJlLXNhZmUtYW5kLTI1Ni1iaXQtc2VjdXJlIQ=="
        
      # Token expiration in milliseconds (e.g. 5000ms = 5s to prevent replay attacks)
      token-expiration-ms: 5000
      allowed-paths:
         - /actuator/health
         - /actuator/info
         
