api:
   paths:
      version: /api/v1
	  # ------------------ Authentication ------------------
	  auth:
	     base: ${api.paths.version}/auth
		 signup: /signup
         signin: /signin
	     signout: /signout
         verify-email: /verify-email
         forgot-password: /forgot-password
         reset-password: /reset-password
         resend-verification: /resend-verification
	     
	  admin-base:
	     base: ${api.paths.version}/admin/auth
	     delete-unverified-accounts: /delete-unverified-accounts
	     find-user: /find-userId
		 
      custom-base: 
	     base: ${api.paths.version}/custom/auth	  

	 #----------- Black list ------------
	  blacklist:  
	     base: ${api.paths.version}/blacklist
         add-jwt: /add-jwt
	     find-jwt: /find-jwt
		 
