api:
   #------------------ Authentication -----------------
   authentication:   
      version: /api/v1
      auth: /auth
	  admin-auth: admin/auth
	  custom-auth: custom/auth
	  signup: /signup
      signin: /signin
	  signout: /signout
      verify-email: /verify-email
      forgot-password: /forgot-password
      reset-password: /reset-password
      resend-verification: /resend-verification
	  delete-unverified-accounts: /delete-unverified-accounts
	  find-user: /find-userId
	  
}
