api:
  paths:
    version: /api/v1
    #------------------ Authentication ------------------
    auth:
      base: ${api.paths.version}/auth
      signup: /signup
      signin: /signin
      signout: /signout
      verify-email: /verify-email
      forgot-password: /forgot-password
      reset-password: /reset-password
      resend-verification: /resend-verification

    auth-admin:
      base: ${api.paths.version}/admin/auth
      delete-unverified-accounts: /delete-unverified-accounts
      
    custom-auth:
      base: ${api.paths.version}/custom/auth
      find-user: /find-userId
    #------------------ Blacklist ------------------
    blacklist:
      base: ${api.paths.version}/blacklist
      add-jwt: /add-jwt
      find-jwt: /find-jwt
      delete-all-jwt: /delete-all-jwt
      
    #------------------ Notification ------------------
    notification:
      base: ${api.paths.version}/notification
      confirm-registration: /confirm-registration
      reset-password: /reset-password
      passwordchanged: /passwordchanged
      temporary-password: /temporary-password
      
      
   
