api:
  paths:
    version: /api/v1
    #------------------ Authentication ------------------
    admin-auth:
      base: ${api.paths.version}/admin/auth
      signup: /signup
      delete-unverified-accounts: /delete-unverified-accounts

    custom-auth:
      base: ${api.paths.version}/custom/auth
      find-user: /find-userId

        
      #base-specifications: ${api.paths.version}/admin/operation/specifications

    #----------------- Secure paths -----------------  
    secure:
      base: ${api.paths.version}/secure

      blacklist:
        base: ${api.paths.version}/secure/blacklist
        delete-all-jwt: /delete-all-jwt
      #------------------ Secure Operation Categories & Specifications ------------------
      operation:
        categories:
          base: ${api.paths.version}/secure/operation/categories
          add-categories: /add-categories
          add-subcategories: /add-subcategories
          add-products: /add-products
          add-brands: /add-brands
          update-categories: /update-categories
          update-subcategories: /update-subcategories
          update-products: /update-products
          update-brands: /update-brands

        specifications:
          base: ${api.paths.version}/secure/operation/specifications

      #------------------ Secure Cache Categories & Specifications ------------------
      cache:
        categories:
          base: ${api.paths.version}/secure/cache/categories
          update: /update
          
    #******************************************************************************** 
    #******************************** Public paths ********************************** 
    #********************************************************************************
    public:
      base: ${api.paths.version}/public

      #------------------ Public Authentication ------------------
      auth:
        base: ${api.paths.version}/public/auth
        signup: /signup
        signin: /signin
        signout: /signout
        verify-email: /verify-email
        forgot-password: /forgot-password
        reset-password: /reset-password
        resend-verification: /resend-verification

      #------------------ Public Blacklist ------------------
      blacklist:
        base: ${api.paths.version}/public/blacklist
        add-jwt: /add-jwt
        find-jwt: /find-jwt

      #------------------ Public Operation Categories ------------------
      operation-categories:
        base: ${api.paths.version}/public/operation/categories
        find-categories: /find-categories
        find-subcategories: /find-subcategories
        find-products: /find-products

      #------------------ Public Operation Specifications ------------------
      operation-specifications:
        base: ${api.paths.version}/public/operation/specifications

      #------------------ Public Cache Categories ------------------
      cache-categories:
        base: ${api.paths.version}/public/cache/categories
        find-category: /find
        find-all: /findAll

      #------------------ Public Cache Specifications ------------------
      cache-specifications:
        base: ${api.paths.version}/public/cache/specifications
      
      
      #------------------ Public Notifications ------------------
      notification:
        base: ${api.paths.version}/public/notification
        confirm-registration: /confirm-registration
        reset-password: /reset-password
        password-changed: /password-changed
        temporary-password: /temporary-password
